#!/bin/bash
./bin/console app:configure-school-search
./bin/console  app:school-data-synchronization dataFiles/schools AB-Elementary 1
./bin/console  app:school-data-synchronization dataFiles/schools AB-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools AB-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools AB-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools BC-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools BC-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools BC-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools BC-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools Elementary_100 0
./bin/console  app:school-data-synchronization dataFiles/schools MB-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools MB-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools MB-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools MB-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools NB-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools NB-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools NB-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools NB-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools NL-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools NL-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools NL-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools NL-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools NS-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools NS-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools NS-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools NS-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools NT-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools NT-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools NT-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools NT-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools ON-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools ON-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools ON-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools ON-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools PE-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools PE-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools PE-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools PE-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools QC-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools QC-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools QC-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools QC-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools SK-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools SK-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools SK-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools SK-Secondary 0
./bin/console  app:school-data-synchronization dataFiles/schools YT-Elementary 0
./bin/console  app:school-data-synchronization dataFiles/schools YT-Middle 0
./bin/console  app:school-data-synchronization dataFiles/schools YT-Preschool 0
./bin/console  app:school-data-synchronization dataFiles/schools YT-Secondary 0